# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -o advent-of-code-2020 main.go
  test:
    cmds:
      - go test ./...
  coverage:
    cmds:
      - go test -coverprofile cp.out ./...
      - rm cp.out
